#!/bin/bash
#$ -cwd
#$ -S /bin/bash
#$ -l p=1

########################### download from GBMI PRS paper #################
##   Input Files

##- Score file (`prsfile`)
#  - suffix with *.profile or .sscore* generated by plink 1.* or plink 2.0
##- Phenotype file (`phenofile`)
#  - Columns include FID, IID and phenotype (from 14 endpoints)
##- Sampel IDs (`popfile`)
#  - List **unrelated individuals** in the target ancestry with FID IID included in the first two columns.
##- Covariate file (`covfile`)
#  - Columns include FID, IID, your **Biobank specific** covariates used in your GWAS analyses
##- PC file (`pcfile`)
#  - Columns include FID, IID, PC1, PC2...

################################################################################
# Please fill in the below variables
################################################################################
Pop="BCY" #e.g., "EUR", BCY: Beijing chaoyang 511 samples
PHENO="COPD" #e.g., "ASTHMA"
covs="age,age2,sex,height,smoke" #e.g, "Age,Sex"
pc_numbers="PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10" ##PC1:PC10 is used by default, please change based on your specific Biobank GWAS analyses.
K=NULL #e.g., 0.58, if not specified, please keep it as NULL, the script will use the proportion of cases in the target population by default
phenofile="/data/wangj/pangjl/COPD_GWAS/VCF_files/validation_set_511samples/pheno.txt" 
popfile="samples_rm_relate3.txt" ### change
#prsfile="PRS.5e-6.profile"
covfile="/data/wangj/pangjl/COPD_GWAS/VCF_files/validation_set_511samples/cov.new.txt"
pcfile="/data/wangj/pangjl/COPD_GWAS/VCF_files/validation_set_511samples/PCs.txt"
cohort="CPH_GBMI_meta" # Your specific Biobank name
ldref="CPHS" # LD reference panel used, e.g., 1KG or UKBB
#out="PRS.5e-6.metrics"

#######################################################
conda activate ggpubr
#pvalue=("auto" "phi_1e-6" "phi_1e-5" "phi_1e-4"  "phi_1e-3" "phi_1e-2" "phi_1e-1" "phi_1")
pvalue=("phi_1e-4")
for i in ${pvalue[@]};
do

prsfile="../PRScs_$i/PRS_cohort1.profile"
out="PRS.$i.metrics.90ci"

Rscript --slave create_prs_metrics.R \
--pop ${Pop} --pheno ${PHENO} \
--covs ${covs} \
--K ${K} \
--pc_numbers ${pc_numbers} \
--phenofile ${phenofile} \
--popfile ${popfile}  \
--prsfile ${prsfile} \
--covfile $covfile \
--pcfile ${pcfile} \
--cohort_name ${cohort} \
--ldref ${ldref} \
--out ${out}

done
