#!/bin/bash
#$ -cwd
#$ -S /bin/bash
#$ -l p=1

########################### download from GBMI PRS paper #################
##   Input Files

##- Score file (`prsfile`)
#  - suffix with *.profile or .sscore* generated by plink 1.* or plink 2.0
##- Phenotype file (`phenofile`)
#  - Columns include FID, IID and phenotype (from 14 endpoints)
##- Sampel IDs (`popfile`)
#  - List **unrelated individuals** in the target ancestry with FID IID included in the first two columns.
##- Covariate file (`covfile`)
#  - Columns include FID, IID, your **Biobank specific** covariates used in your GWAS analyses
##- PC file (`pcfile`)
#  - Columns include FID, IID, PC1, PC2...

################################################################################
# Please fill in the below variables
################################################################################
Pop="CPH" #e.g., "EUR", BCY: Beijing chaoyang 511 samples
PHENO="COPD" #e.g., "ASTHMA"
covs="age,age2,sex,height,smoke" #e.g, "Age,Sex"
pc_numbers="PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10" ##PC1:PC10 is used by default, please change based on your specific Biobank GWAS analyses.
K=NULL #e.g., 0.58, if not specified, please keep it as NULL, the script will use the proportion of cases in the target population by default
phenofile="/data/wangj/pangjl/COPD_GWAS/VCF_files/validation_set_511samples/pheno.txt"
popfile="/data/wangj/pangjl/COPD_GWAS/VCF_files/validation_set_511samples/pop.txt"
covfile="/data/wangj/pangjl/COPD_GWAS/VCF_files/validation_set_511samples/cov.new.txt"
pcfile="/data/wangj/pangjl/COPD_GWAS/VCF_files/validation_set_511samples/PCs.txt"
cohort="GBMI_meta" # Your specific Biobank name
ldref="CPHS" # LD reference panel used, e.g., 1KG or UKBB

#######################################################
conda activate ggpubr

arr=("5e-8" "5e-7" "5e-6" "5e-5" "5e-4" "1e-7" "1e-6" "1e-5" "1e-4" "0.001" "0.01" "0.05" "0.1" "0.2" "0.5" "1")
for i in ${arr[@]}
do
prsfile="PRS.$i.profile"
out="PRS.$i.metrics"


Rscript --slave create_prs_metrics.R \
--pop ${Pop} --pheno ${PHENO} \
--covs ${covs} \
--K ${K} \
--pc_numbers ${pc_numbers} \
--phenofile ${phenofile} \
--popfile ${popfile}  \
--prsfile ${prsfile} \
--covfile $covfile \
--pcfile ${pcfile} \
--cohort_name ${cohort} \
--ldref ${ldref} \
--out ${out}

done
